<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Poll Pad 3 Version</name>
   <tag></tag>
   <elementGuidId>a57a6423-4e31-4eeb-b1b7-a715674c6817</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name = 'account[poll_pad_3_version]' and @id = 'account_poll_pad_3_version' and (text() = '
                      1.0.1
                      1.1.0
                      1.2.canada
                      1.3.0
                      1.3.1
                      1.3.3
                      1.3.4
                      1.3.5
                      2.0.canada
                      2.0.1
                      2.1.0
                      2.1.1
                      2.1.2
                      2.1.3
                      2.1.4
                      2.1.5
                      2.1.6
                      2.1.7
                      2.1.8
                      2.1.9
                      2.1.10
                      2.1.11
                      2.2.0
                      2.3.0
                      unstable-test' or . = '
                      1.0.1
                      1.1.0
                      1.2.canada
                      1.3.0
                      1.3.1
                      1.3.3
                      1.3.4
                      1.3.5
                      2.0.canada
                      2.0.1
                      2.1.0
                      2.1.1
                      2.1.2
                      2.1.3
                      2.1.4
                      2.1.5
                      2.1.6
                      2.1.7
                      2.1.8
                      2.1.9
                      2.1.10
                      2.1.11
                      2.2.0
                      2.3.0
                      unstable-test')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='account_poll_pad_3_version']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account[poll_pad_3_version]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_poll_pad_3_version</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      1.0.1
                      1.1.0
                      1.2.canada
                      1.3.0
                      1.3.1
                      1.3.3
                      1.3.4
                      1.3.5
                      2.0.canada
                      2.0.1
                      2.1.0
                      2.1.1
                      2.1.2
                      2.1.3
                      2.1.4
                      2.1.5
                      2.1.6
                      2.1.7
                      2.1.8
                      2.1.9
                      2.1.10
                      2.1.11
                      2.2.0
                      2.3.0
                      unstable-test</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_poll_pad_3_version&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='account_poll_pad_3_version']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='admin-account-edit-page']/div/div/div[8]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Poll pad 3 version'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pad type'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seal'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scan ID'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[8]/select</value>
   </webElementXpaths>
</WebElementEntity>
